"""
backend/pdf_report.py
Purpose: Generate a downloadable PDF report for a single patient prediction
(risk or recurrence), including the prediction, probability, key input
values, and the top SHAP feature contributions. Satisfies the proposal's
"Exportable model cards and risk reports (PDF)" requirement.
"""
from fpdf import FPDF
from datetime import datetime
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class ReportPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(20, 80, 120)
        self.cell(0, 10, 'ThyroidCare - Prediction Report', ln=True, align='C')
        self.set_font('Helvetica', '', 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, datetime.now().strftime('Generated: %Y-%m-%d %H:%M'), ln=True, align='C')
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, 'For research/educational purposes only - not a substitute for clinical diagnosis.', align='C')


def generate_prediction_pdf(module: str, patient: dict, result: dict, output_path: str):
    """
    module: 'risk' or 'recurrence'
    patient: raw input dict used for the prediction
    result: the dict returned by predict_risk() / predict_recurrence()
    output_path: where to save the PDF file
    """
    pdf = ReportPDF()
    pdf.add_page()

    # ---- Section: Prediction Summary ----
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f'Module: {"Risk Prediction" if module == "risk" else "Recurrence Prediction"}', ln=True)

    pdf.set_font('Helvetica', '', 12)
    if module == 'risk':
        pdf.cell(0, 8, f"Diagnosis Prediction: {result['diagnosis']}", ln=True)
        pdf.cell(0, 8, f"Malignant Probability: {result['malignant_probability']:.1%}", ln=True)
        pdf.cell(0, 8, f"Risk Level: {result['risk_level']}", ln=True)
    else:
        pdf.cell(0, 8, f"Recurrence Prediction: {result['recurred_prediction']}", ln=True)
        pdf.cell(0, 8, f"Recurrence Probability: {result['recurrence_probability']:.1%}", ln=True)

    pdf.ln(4)

    # ---- Section: Patient Input Summary ----
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'Input Summary', ln=True)
    pdf.set_font('Helvetica', '', 10)
    for key, value in patient.items():
        pdf.cell(0, 6, f'  {key}: {value}', ln=True)

    pdf.ln(4)

    # ---- Section: Top Contributing Factors (SHAP) ----
    if 'shap_explanation' in result:
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 8, 'Top Contributing Factors (SHAP)', ln=True)
        pdf.set_font('Helvetica', '', 10)
        for item in result['shap_explanation']:
            direction = 'increases' if item['impact'] > 0 else 'decreases'
            pdf.cell(0, 6, f"  {item['feature']}: {direction} risk (impact {item['impact']:+.3f})", ln=True)

    pdf.ln(6)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 5,
        'Disclaimer: This report is generated by an AI research prototype (ThyroidCare) '
        'for academic and educational purposes only. It is NOT a validated diagnostic tool '
        'and must not be used as the sole basis for any clinical decision.'
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path
